import React from "react";
import type { Metadata } from "next";

import { auth } from "@clerk/nextjs";
import Dropzone from "@/components/Dropzone";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

function Dashboard() {
  const {userId} = auth();
  return <div className="h-screen -mb-64">
    <Dropzone />
  </div>;
}

export default Dashboard;
